// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as wailsui$0 from "../../../../../uniclog.io/sonoryx/internal/ui/wails/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "audio-meter": wailsui$0.AudioMeterDTO;
            "client-event-log-changed": boolean;
            "client-state-changed": boolean;
            "server-status-changed": boolean;
            "tray-screen-share": boolean;
        }
    }
}
