// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Snapshot {
    "current": string;
    "available": string;
    "minServer": string;
    "availableMinServer": string;
    "status": string;
    "error": string;
    "written": number;
    "total": number;
    "releaseURL": string;
}
