// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Cancel(): $CancellablePromise<void> {
    return $Call.ByID(3303922594);
}

export function Check(): $CancellablePromise<void> {
    return $Call.ByID(1617665808);
}

export function ConfirmStartup(): $CancellablePromise<void> {
    return $Call.ByID(3151328313);
}

export function Download(): $CancellablePromise<void> {
    return $Call.ByID(763313144);
}

export function Restart(): $CancellablePromise<void> {
    return $Call.ByID(4211883811);
}

export function Snapshot(): $CancellablePromise<$models.Snapshot> {
    return $Call.ByID(3221952908);
}
