// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Cancel(): $CancellablePromise<void> {
    return $Call.ByID(3285178305);
}

export function Check(): $CancellablePromise<void> {
    return $Call.ByID(3617400105);
}

export function ConfirmStartup(): $CancellablePromise<void> {
    return $Call.ByID(806825094);
}

export function Download(): $CancellablePromise<void> {
    return $Call.ByID(4089170227);
}

export function Restart(): $CancellablePromise<void> {
    return $Call.ByID(2797828238);
}

export function Snapshot(): $CancellablePromise<$models.Snapshot> {
    return $Call.ByID(3140586591);
}
