// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface AudioDeviceDTO {
    "id": string;
    "name": string;
    "isDefault": boolean;
}

export interface AudioDevicesDTO {
    "capture": AudioDeviceDTO[] | null;
    "playback": AudioDeviceDTO[] | null;
    "selectedCapture": string;
    "selectedPlayback": string;
}

export interface AudioMeterDTO {
    "input": number;
    "processed": number;
    "transmitted": number;
}

export interface AudioProfileDTO {
    "codec": string;
    "sampleRate": number;
    "channels": number;
    "frameDurationMs": number;
    "bitrate": number;
    "application": string;
}

export interface AudioStateDTO {
    "muted": boolean;
    "deafened": boolean;
    "captureAvailable": boolean;
    "rnnoiseEnabled": boolean;
    "rnnoiseSensitivity": number;
    "vadEnabled": boolean;
    "vadMode": string;
    "vadSensitivity": number;
    "vadOpen": boolean;
}

export interface ChannelDTO {
    "id": string;
    "parentId": string;
    "name": string;
    "topic": string;
    "description": string;
    "position": number;
    "maxUsers": number;
    "canJoin": boolean;
    "audio": AudioProfileDTO;
}

export interface ClientEventDTO {
    "sequence": string;
    "time": string;
    "kind": string;
    "message": string;
    "revision"?: string;
}

export interface ClientViewDTO {
    "connectionStatus": string;
    "lastError"?: string;
    "server": ServerDTO;
    "revision": string;
    "sessionId": string;
    "channelId": string;
    "canKick": boolean;
    "canBan": boolean;
    "canDrag": boolean;
    "snapshotFresh": boolean;
    "channels": ChannelDTO[] | null;
    "participants": ParticipantDTO[] | null;
    "screenStreams": ScreenStreamDTO[] | null;
    "audio": AudioStateDTO;
}

export interface ConnectRequest {
    "name": string;
    "server": string;
    "minServerVersion"?: string;
}

export interface ConnectionStatsDTO {
    "sessionId": string;
    "generation": string;
    "status": string;
    "pingMs": number;
    "pingVariationMs": number;
    "pingAvailable": boolean;
    "pingVariationAvailable": boolean;
    "pingSampleAtMs": number;
    "incomingLoss": number;
    "incomingKnown": boolean;
    "incomingSampleAtMs": number;
    "outgoingLoss": number;
    "outgoingKnown": boolean;
}

export interface MediaTrustDTO {
    "fingerprint": string;
    "trusted": boolean;
    "known": boolean;
}

export interface ParticipantDTO {
    "sessionId": string;
    "displayName": string;
    "channelId": string;
    "speaking": boolean;
    "local": boolean;
}

export interface ScreenStreamDTO {
    "id": string;
    "ownerSessionId": string;
    "channelId": string;
}

export interface ServerDTO {
    "name": string;
}
