// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as clientapp$0 from "../../clientapp/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as mediasignal$0 from "../../mediasignal/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AudioDevices(): $CancellablePromise<$models.AudioDevicesDTO> {
    return $Call.ByID(4163031362);
}

export function Ban(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(2103541416, sessionID);
}

export function Chat(request: $models.ChatRequestDTO): $CancellablePromise<$models.ChatPageDTO> {
    return $Call.ByID(1571062045, request);
}

export function CloseToTray(): $CancellablePromise<boolean> {
    return $Call.ByID(846043856);
}

export function Connect(request: $models.ConnectRequest): $CancellablePromise<void> {
    return $Call.ByID(1135091607, request);
}

export function ConnectionStats(): $CancellablePromise<$models.ConnectionStatsDTO> {
    return $Call.ByID(166964494);
}

export function DeleteRecentServer(address: string): $CancellablePromise<void> {
    return $Call.ByID(1322328776, address);
}

export function Disconnect(): $CancellablePromise<void> {
    return $Call.ByID(2989955305);
}

export function Drag(sessionID: string, channelID: string): $CancellablePromise<void> {
    return $Call.ByID(3258615617, sessionID, channelID);
}

export function EventsAfter(sequence: string): $CancellablePromise<$models.ClientEventDTO[] | null> {
    return $Call.ByID(1061099244, sequence);
}

export function JoinChannel(channelID: string): $CancellablePromise<void> {
    return $Call.ByID(734772938, channelID);
}

export function Kick(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(2906324561, sessionID);
}

/**
 * LogDiagnostic receives infrequent browser-side lifecycle events. It accepts
 * bounded text only; callers must not pass SDP, credentials or media content.
 */
export function LogDiagnostic(operation: string, message: string): $CancellablePromise<void> {
    return $Call.ByID(2427776576, operation, message);
}

export function MediaServerIdentity(): $CancellablePromise<$models.MediaTrustDTO> {
    return $Call.ByID(869671352);
}

export function OpenScreenWindow(streamID: string, ownerName: string): $CancellablePromise<void> {
    return $Call.ByID(3243961435, streamID, ownerName);
}

export function ParticipantVolume(sessionID: string): $CancellablePromise<number> {
    return $Call.ByID(2374739398, sessionID);
}

export function PublishScreen(offer: mediasignal$0.SessionDescription): $CancellablePromise<clientapp$0.MediaPublishResult> {
    return $Call.ByID(1165940958, offer);
}

export function RecentServers(): $CancellablePromise<$models.RecentServerDTO[] | null> {
    return $Call.ByID(3357885992);
}

export function ReconnectServer(address: string): $CancellablePromise<void> {
    return $Call.ByID(1012485691, address);
}

export function RefreshServerStatuses(): $CancellablePromise<void> {
    return $Call.ByID(1470301523);
}

export function SavedDisplayName(): $CancellablePromise<string> {
    return $Call.ByID(1402910199);
}

export function SetCaptureDevice(id: string): $CancellablePromise<void> {
    return $Call.ByID(3622601723, id);
}

export function SetCloseToTray(value: boolean): $CancellablePromise<void> {
    return $Call.ByID(2664460774, value);
}

export function SetDeafened(value: boolean): $CancellablePromise<void> {
    return $Call.ByID(3554619559, value);
}

export function SetMicrophoneGain(value: number): $CancellablePromise<void> {
    return $Call.ByID(2067370678, value);
}

/**
 * SetMicrophoneMonitor plays the preview's transmitted audio back to the user.
 */
export function SetMicrophoneMonitor(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(563032017, enabled);
}

/**
 * SetMicrophonePreview runs the microphone pipeline for the settings meter
 * while disconnected; a connected session already feeds the meter.
 */
export function SetMicrophonePreview(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(4214796911, enabled);
}

export function SetMuted(value: boolean): $CancellablePromise<void> {
    return $Call.ByID(3550928604, value);
}

export function SetParticipantVolume(sessionID: string, value: number): $CancellablePromise<void> {
    return $Call.ByID(974686508, sessionID, value);
}

export function SetPlaybackDevice(id: string): $CancellablePromise<void> {
    return $Call.ByID(3783657834, id);
}

export function SetRNNoiseEnabled(value: boolean): $CancellablePromise<void> {
    return $Call.ByID(115474106, value);
}

export function SetRNNoiseSensitivity(value: number): $CancellablePromise<void> {
    return $Call.ByID(2007323576, value);
}

export function SetServerAlias(address: string, alias: string): $CancellablePromise<void> {
    return $Call.ByID(259081090, address, alias);
}

export function SetServerFavorite(address: string, favorite: boolean): $CancellablePromise<void> {
    return $Call.ByID(1793569962, address, favorite);
}

export function SetTheme(value: string): $CancellablePromise<void> {
    return $Call.ByID(338374198, value);
}

export function SetVADEnabled(value: boolean): $CancellablePromise<void> {
    return $Call.ByID(141342905, value);
}

export function SetVADMode(value: string): $CancellablePromise<void> {
    return $Call.ByID(3672257083, value);
}

export function SetVADSensitivity(value: number): $CancellablePromise<void> {
    return $Call.ByID(766836891, value);
}

export function Snapshot(): $CancellablePromise<$models.ClientViewDTO> {
    return $Call.ByID(1939529571);
}

export function StopScreen(streamID: string): $CancellablePromise<void> {
    return $Call.ByID(4041861463, streamID);
}

export function SubscribeScreen(streamID: string, subscriberID: string, offer: mediasignal$0.SessionDescription): $CancellablePromise<clientapp$0.MediaSubscribeResult> {
    return $Call.ByID(3370288729, streamID, subscriberID, offer);
}

export function Theme(): $CancellablePromise<string> {
    return $Call.ByID(3211887612);
}

export function TrustMediaServer(fingerprint: string): $CancellablePromise<void> {
    return $Call.ByID(2472361038, fingerprint);
}

export function UnsubscribeScreen(streamID: string, subscriberID: string): $CancellablePromise<void> {
    return $Call.ByID(3899704880, streamID, subscriberID);
}
